# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Oct 16 12:57:28 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

def test():
	print 'TEST'

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(752, 584)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.comboBox = QtGui.QComboBox(self.centralWidget)
        self.comboBox.setGeometry(QtCore.QRect(430, 30, 101, 31))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(290, 120, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(430, 140, 131, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.spectralView = QtGui.QGraphicsView(self.centralWidget)
        self.spectralView.setGeometry(QtCore.QRect(280, 240, 461, 281))
        self.spectralView.setFrameShape(QtGui.QFrame.WinPanel)
        self.spectralView.setObjectName(_fromUtf8("spectralView"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(10, 220, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(430, 120, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(430, 160, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(280, 220, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(430, 0, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.listWidget = QtGui.QListWidget(self.centralWidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 240, 256, 281))
        self.listWidget.setFrameShape(QtGui.QFrame.WinPanel)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.pushButton_3 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(640, 70, 91, 31))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton = QtGui.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(640, 30, 91, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.exposureLCD = QtGui.QLCDNumber(self.centralWidget)
        self.exposureLCD.setGeometry(QtCore.QRect(290, 140, 111, 61))
        self.exposureLCD.setObjectName(_fromUtf8("exposureLCD"))
        self.exposureDial = QtGui.QDial(self.centralWidget)
        self.exposureDial.setGeometry(QtCore.QRect(290, 20, 101, 101))
        self.exposureDial.setMaximum(100)
        self.exposureDial.setNotchesVisible(True)
        self.exposureDial.setObjectName(_fromUtf8("exposureDial"))
        self.progressBar = QtGui.QProgressBar(self.centralWidget)
        self.progressBar.setGeometry(QtCore.QRect(430, 180, 301, 23))
        self.progressBar.setAutoFillBackground(True)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.pushButton_2 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 30, 91, 31))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.internetSpectralDatabaseList = QtGui.QListWidget(self.centralWidget)
        self.internetSpectralDatabaseList.setGeometry(QtCore.QRect(10, 20, 256, 192))
        self.internetSpectralDatabaseList.setFrameShape(QtGui.QFrame.WinPanel)
        self.internetSpectralDatabaseList.setObjectName(_fromUtf8("internetSpectralDatabaseList"))
        item = QtGui.QListWidgetItem()
        self.internetSpectralDatabaseList.addItem(item)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 752, 19))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.exposureDial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.exposureLCD.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "plot.ly", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "phant", None))
        self.label_4.setText(_translate("MainWindow", "CCD Exposure Time", None))
        self.label.setText(_translate("MainWindow", "Internet Spectral Database:", None))
        self.label_2.setText(_translate("MainWindow", "Compounds List:", None))
        self.label_6.setText(_translate("MainWindow", "Sample Name", None))
        self.label_5.setText(_translate("MainWindow", "Capture progress", None))
        self.label_3.setText(_translate("MainWindow", "Spectra", None))
        self.label_7.setText(_translate("MainWindow", "ramanPi - spectraCide V0.1", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Aliphatic compounds", None))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "alkanes", None))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "halogenoalkanes", None))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "alcohols", None))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "aldehydes and ketones", None))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "carboxylic acids", None))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "acyl chlorides", None))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "acid anhydrides", None))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "esters", None))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "amides", None))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "nitriles", None))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "amines", None))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "amino acides etc", None))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", "Aromatic compounds", None))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", "arenes", None))
        item = self.listWidget.item(15)
        item.setText(_translate("MainWindow", "aryl halides", None))
        item = self.listWidget.item(16)
        item.setText(_translate("MainWindow", "phenol", None))
        item = self.listWidget.item(17)
        item.setText(_translate("MainWindow", "phenylamine", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_3.setText(_translate("MainWindow", "Save Spectra", None))
        self.pushButton.setText(_translate("MainWindow", "Get Spectra", None))
        self.pushButton_2.setText(_translate("MainWindow", "Post Spectra", None))
        __sortingEnabled = self.internetSpectralDatabaseList.isSortingEnabled()
        self.internetSpectralDatabaseList.setSortingEnabled(False)
        item = self.internetSpectralDatabaseList.item(0)
        item.setText(_translate("MainWindow", "RRUFF ", None))
        self.internetSpectralDatabaseList.setSortingEnabled(__sortingEnabled)

#if __name__ == "__main__":
def main():
	import sys
	app = QtGui.QApplication(sys.argv)
	MainWindow = QtGui.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())

main()